### ISSUE TITLE
Future of shinyCohortBuilder (and cohortBuilder)?

### ISSUE THREAD

**Issue by JustGitting** [r-world-devs/shinyCohortBuilder#49]
Hi @krystian8207, @galachad,

I was looking at a way to add multiple filters to a shiny app but could see this could get complex. In my search for best practices I found your R packages, shinyCohortBuilder and cohortBuilder. They look like a fantastic idea and would make it a lot easier.

Before I commit the time/energy integrating shinyCohortBuilder into my shiny app, I wanted to know the future of these packages.

Is (shiny)cohortBuilder still being developed as it's been a little quiet of late with about 30 issues/features/improvements pending?

Thank you!

**Comment by krystian8207** [comment]
Hi @JustGitting.

Yes, the package is still developed. 

We're actively using the package in our internal projects and gather new ideas and requirements as issues here.
We're mostly developing the package during our working hours (depending on our resources), so bugfixes have priority here. That's why it may look being stale. Nevertheless amid Q1/Q2 this year we plan to allocate more of our resources on those packages and release a new version that will close many of the existing issues.

Feel free to use (shiny)CohortBuilder and don't hesitate to ask any related questions along with filing issues in case of need.

Best,
Krystian

**Comment by JustGitting** [comment]
@krystian8207 Thank you for the background.

Great news this will get better, it's such a common problem to need multiple filters.

I'll raise an issue if I find any problems.
